all: mrb_eval.dll

mrb_eval.dll : mrb_eval.obj
	link -dll mrb_eval.obj user32.lib mruby.lib mrbc.lib /nodefaultlib:libcmt

mrb_eval.obj : mrb_eval.cc
	cl -EHsc -DMYSQL_DYNAMIC_PLUGIN -c -I../mruby/include -Ic:/progra~1/mysql/mysqls~1.5/include mrb_eval.cc
